### ISSUE TITLE
게시글 기능 고도화4

### ISSUE THREAD

**Issue by leejh7** [capstone-maru/maru-back-end#112]
## Overview
- 변경 된 기획 적용

## Task
- [x] 게시글 기획 변경
  - [x] 모집 된 메이트
    - [x] POST
    - [x] GET
  - [x] 방 정보
    - [x] 월세 제거
    - [x] 월 분담금 추가
    - [x] 화장실 개수 추가
    - [x] 거실 유무 추가
    - [x] 층 (지상, 반지하, 옥탑방) 추가
    - [x] 추가 옵션 추가
  - [x] 위치 정보
    - [x] 도시, 도로명 주소, 지번 주소 제외하고 제거
