### ISSUE TITLE
채팅 기능

### ISSUE THREAD

**Issue by cheesecrust** [capstone-maru/maru-back-end#114]
## Overview

채팅 기능 고도화

## Additional context

채팅 기능 고도화를 위한 chatRoom, chat domain 생성, charRoom, member 관계 만들어주기

## Tasks

- [x] chatRoom 생성
- [x] chatRoom 관리 로직 생성
- [ ] 최근 채팅 불러오기
- [ ] response type 맞추기
