### ISSUE TITLE
2024-03-11 진행한 코드 리뷰 리팩토링 

### ISSUE THREAD

**Issue by leejh7** [capstone-maru/maru-back-end#12]
## Overview
#2 기능을 구현한 후 코드 리뷰를 통해 필요한 부분에 있어 코드 리팩토링 함

## Task
- [x] JpaConfig auditorAware() 메서드 리팩토링
- [x] Builder 패턴 적용
- [x] application.yaml 파일 보안 강화하기
- [x] ~~KakaoOAuth2Response 필드 수정~~

## Notify
~~Hashicorp Vault를 사용하기 위해 의존성을 주입하였다. 
build.gradle 파일에 dependencyManagement를 건드렸기 때문에 추후에 Querydsl을 사용하기 위해 의존성을 추가할 때 버젼을 수기로 작성해야 이슈 없이 작동시킬 수 있다.~~

**_수정_**
개발 단계에서는 Vault를 in-memory 방식으로 사용할 수 밖에 없기 때문에 로컬에서 Vault 서버를 껏다 키면 기존에 설정해놓은 KV가 사라진다.
따라서 개발 단계에서는 환경변수를 이용하여 시크릿 키 값을 감추는 방식을 채택하고 클라우드에 서버를 올릴 때 Vault를 도입하는 방식을 채택하도록 한다.
