### ISSUE TITLE
게시글 기능 고도화6

### ISSUE THREAD

**Issue by leejh7** [capstone-maru/maru-back-end#184]
## Overview
필요한 추가 게시글 기능을 구현

## Task
- [x] 사용자별 게시글 목록
- [ ] 유저의 맞팔 관계의 유저 불러오기
- [x] 게시글 작성시 메이트 카드에 location 이 비어있는 문제 해결
