### ISSUE TITLE
make profile 

### ISSUE THREAD

**Issue by cheesecrust** [capstone-maru/maru-back-end#47]
## Overview

made user profile by user custom data

## Tasks

- [ ] test code 작성
- [x] controller 작성
- [x] db modeling
- [x] service 작성
    - [x] 멤버 생성시 카드 자동 생성
    - [x] 카드 특성 수정 기능
- [ ] initialized 값 불러올떄 projection 사용
- [x] 팔로우 팔로잉 기능
