### ISSUE TITLE
데이터베이스 설정, 더미 데이터 생성

### ISSUE THREAD

**Issue by leejh7** [capstone-maru/maru-back-end#51]
## Overview
프로젝트에서 사용하기로 한 DBMS는 PostgreSQL 이다.
로컬 PC에 [postgresql](https://www.postgresql.org/download)을 다운로드 받고 spring boot와 연결시키는 설정 작업을 한다.
[mockaroo](https://www.mockaroo.com)를 이용하여 MemberAccount와 SharedPost의 더미 데이터를 생성한다.

## Task
- [x] postgresql 다운로드 받기
- [x] build.gradle에 postgresql connector 라이브러리 추가하기
- [x] application.yml에 postgresql 설정하기
- [x] [ERD](https://www.erdcloud.com/d/e6DuawPM53m4Pg5oN)를 참고하여 MemberAccount, SharedPost 테이블 작성하기
- [x] 더미 데이터 생성하기
