### ISSUE TITLE
게시판 기능 구현

### ISSUE THREAD

**Issue by leejh7** [capstone-maru/maru-back-end#52]
## Overview
메이트 찾기(게시판) 페이지 기능 구현

## Task
- [x] 게시판 (=전체 게시글 불러오기) 기능 구현 (READ)
  - [x] SharedRoomRepository 작성
  - [x] SharedRoomService 작성
  - [x] 필요한 DTO 작성 (ResponseDTO, DTO)
  - [x] SharedRoomController 작성
- [x] 필터링 기능 구현
  - [x] 방 종류(다중 선택 가능)에 따른 필터링
  - [x] 거래 종류(다중 선택 가능)에 따른 필터링
- [x] 검색어 기능 구현
- [x] 테스트
