### ISSUE TITLE
게시글 기능 고도화

### ISSUE THREAD

**Issue by leejh7** [capstone-maru/maru-back-end#59]
## Overview
현재 게시글 이미지 기능이 구현 되어 있지 않음.
Figma를 참고하여 메이트 있는 게시글에 필요한 정보 추가해야 함.
예외 처리와 검증 도입

## Task
- [x] 게시글 엔티티 수정
  - [x] Address
    - [x] 지하철역 - String
    - [x] 지하철역까지 걸리는 시간 - Short
    - [x] 버스정류장까지 걸리는 시간 - Short
    - [x] 학교 - String
    - [x] 학교까지 걸리는 시간 - Short
    - [x] 편의점까지 걸리는 시간 - Short
  - [x] 모집 인원 - Short
  - [x] 거래 정보
    - [x] 월세 - Long
- [x] 게시글 엔티티 필드 타입 체크하기
