### ISSUE TITLE
게시글 기능 고도화2

### ISSUE THREAD

**Issue by leejh7** [capstone-maru/maru-back-end#69]
## Overview
- 게시글 스크랩 기능 구현 

## Tasks
- [x] 게시글 스크랩 기능 구현
  - [x] 게시글 스크랩 POST 기능 구현
  - [x] 게시글의 스크랩 여부를 response 객체에 넣어주기
  - [x] 상세 게시글 스크랩 개수 기능 구현
  - [x] 상세 게시글 스크랩 개수 response 객체에 넣어주기

## Issues
Notion Issue Tracker에 기능을 구현하면서 직면했던 이슈들과 해결 방법을 작성함
