### ISSUE TITLE
로그인 기능 고도화

### ISSUE THREAD

**Issue by leejh7** [capstone-maru/maru-back-end#9]
# Overview
OAuth 로그인 기능을 고도화하고 마루 서비스에 알맞는 인증, 인가 절차를 추가하는 작업을 진행한다.

## 고도화
- [x] 로그인시 사용자가 회원가입인지 아닌지 판단후 반환
- [x] error handling ( 같은 이메일로 로그인시 error 발생 ) 
- [x] ~~OIDC 도입하기~~
### JWT
- [x] JWT token Provider 구현
- [x] 로그인한 사용자에게 token 값 응답해주기
- [x] 로그인을 제외한 클라이언트의 요청은 TokenFilter로 인증, 인가해주기
  - [x] 서비스에서 자주 사용하는 정보는 token에 넣어놓기 (id, email, nickname, gender, age)
- [x] 프론트에게 토큰 값을 Set-Cookie 하도록 응답하기

**TODO**
- [x] 특정 url은 TokenFilter를 타지 않도록 수정하기
- [x] JWT token ReIssuer 구현
  - [x] 리프레시 토큰 기능 구현
- [x] MVC 영역의 테스트를 원활하게 하기 위해 SecurityConfig 분리하기
- [x] 로그아웃 시 토큰을 삭제하도록 구현
  - [x] SecurityConfig에 logout() 설정하기
- [x] SharedPostPrincipal, Authentication 다향성 고려한 코드로 리팩토링 하기
