### ISSUE TITLE
추천시스템을 위한 domain 수정

### ISSUE THREAD

**Issue by cheesecrust** [capstone-maru/maru-back-end#94]
## Overview

cluster id column 추가
member card에서 member와 room 판별
feature nullable false

## Tasks

- [x] cluster id column 추가 - 추천 시스템에서 cluster id 를 들고 있기 때문에
- [x] member card에서 member와 room 판별
- [x] feature nullable false
