### ISSUE TITLE
room post 작성 시 feature card 생성

### ISSUE THREAD

**Issue by cheesecrust** [capstone-maru/maru-back-end#97]
## Overview

room post 작성 시 게시글에 따른 feature card 생성

## Tasks

- [ ] domain에 field 추가
- [ ] controller dto 수정
- [ ] form-data type 수정
